package campus_quest;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.*;

public class Campus {
	// Map of Rooms to Map of Directions to Neighboring Rooms
	// Map<Room, Map<Direction, Room>>
    public final Map<String, Map<String, String>> map;

    public Campus() {
    	String my_name = "Professor Rhode";
    	this.map = getFroshLevelMap(my_name);
        //this.map = getUpperLevelMap(my_name);
    }

    public Map<String, String> getDirectionsToRoomsMap(String room_name) {
        return map.getOrDefault(room_name, Collections.emptyMap());
    }

    public Set<String> getRoomNames() {
        return map.keySet();
    }

   
    // the key of the map is the Room name
    // the value of the map is another map: the directionsToRoomsMap
    //   directionsToRoomsMap: 
    //       key: direction (N,S,E,W) or item
    //       value: name of next room corresponding to direction, or, name of item
  
    @SuppressWarnings("unused") 
 	private Map<String, Map<String, String>> getFroshLevelMap(String name) {
    	
    	System.out.println("Loading map for: "+ name);
		if(name.equals("Professor Rhode")) {
			System.out.println("ERROR: UNABLE TO LOAD MAP, USE YOUR OWN NAME!");
			return new HashMap<>();
		}
		
         Map<String, Map<String, String>> map = new LinkedHashMap<>();

         map.put("Dorm Room", Map.of(
             "E", "Computer Lab"
         ));

         map.put("Computer Lab", Map.of(
             "W", "Dorm Room",
             "E", "Cafeteria",
             "item", "laptop"
         ));

         map.put("Cafeteria", Map.of(
             "W", "Computer Lab",
             "E", "Library",
             "item", "coffee"
         ));

         map.put("Library", Map.of(
             "W", "Cafeteria",
             "item", "notebook"
         ));

         map.put("Classroom", Map.of(
             "W", "Library"
         ));
         
         return map;
     }
    
    @SuppressWarnings("unused")
    private static Map<String, Map<String, String>>  getUpperLevelMap(String name) {
    	
    		System.out.println("Loading map for: "+ name);
    		if(name.equals("Professor Rhode")) {
    			System.out.println("ERROR: UNABLE TO LOAD MAP, USE YOUR OWN NAME!");
    			return new HashMap<>();
    		}	

	String list_binary = "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAAHdwQAAAAHdARAck8wQUJYTnlBQmRxWVhaaExuVjBhV3d1VEdsdWEy"
                    + "VmtTR0Z6YUUxaGNEVEFUbHdRYk1EN0FnQUJXZ0FMWVdOalpYTnpUM0prWlhKNGNnQVJhbUYyWVM1MWRHbHNMa2hoYzJoTllYQUZCOXJCd3haZzBRTUFBa1lB"
                    + "Q214dllXUkdZV04wYjNKSkFBbDBhSEpsYzJodmJHUjRjRDlBQUFBQUFBQU1kd2dBQUFBUUFBQUFDblFBQ1VSdmNtMGdVbTl2YlhOeEFINEFBVDlBQUFBQUFB"
                    + "QUJkd2dBQUFBQ0FBQUFBWFFBQVZOMEFBbERZV1psZEdWeWFXRjRjUUIrQUFaemNRQitBQUUvUUFBQUFBQUFCbmNJQUFBQUNBQUFBQVYwQUFScGRHVnRkQUFH"
                    + "WTI5bVptVmxjUUIrQUFWMEFBZE1hV0p5WVhKNWRBQUJSWFFBREV4bFkzUjFjbVVnU0dGc2JIUUFBVTV4QUg0QUEzUUFBVmQwQUJKUWNtOW1aWE56YjNJbmN5"
                    + "QlBabVpwWTJWNGNRQitBQXB6Y1FCK0FBRS9RQUFBQUFBQUJuY0lBQUFBQ0FBQUFBVnhBSDRBQ0hRQUNHNXZkR1ZpYjI5cmNRQitBQVYwQUE1VGRIVmtaVzUw"
                    + "SUVObGJuUmxjbkVBZmdBTGRBQVBSV3hsWTNSeWIyNXBZM01nVEdGaWNRQitBQTF4QUg0QUJuRUFmZ0FPZEFBTVEyOXRjSFYwWlhJZ1RHRmllSEVBZmdBU2Mz"
                    + "RUFmZ0FCUDBBQUFBQUFBQU4zQ0FBQUFBUUFBQUFEY1FCK0FBMXhBSDRBQ25FQWZnQUlkQUFGWm14NVpYSnhBSDRBQlhRQURFRmtiV2x1SUU5bVptbGpaWGh4"
                    + "QUg0QUZITnhBSDRBQVQ5QUFBQUFBQUFEZHdnQUFBQUVBQUFBQTNFQWZnQUxjUUIrQUFweEFINEFDSFFBQm14aGNIUnZjSFFBQVZkMEFBbERiR0Z6YzNKdmIy"
                    + "MTRjUUIrQUJOemNRQitBQUUvUUFBQUFBQUFBM2NJQUFBQUJBQUFBQU54QUg0QUNIUUFDbUp5WldGa1ltOWhjbVJ4QUg0QURYRUFmZ0FNY1FCK0FBNXhBSDRB"
                    + "Q25oeEFINEFEM054QUg0QUFUOUFBQUFBQUFBQmR3Z0FBQUFDQUFBQUFYRUFmZ0FMY1FCK0FBWjRjUUIrQUF4emNRQitBQUUvUUFBQUFBQUFBM2NJQUFBQUJB"
                    + "QUFBQUp4QUg0QURuRUFmZ0FHY1FCK0FBVnhBSDRBRTNoeEFINEFGM054QUg0QUFUOUFBQUFBQUFBQmR3Z0FBQUFDQUFBQUFYRUFmZ0FOY1FCK0FCSjRjUUIr"
                    + "QUJ0emNRQitBQUUvUUFBQUFBQUFBWGNJQUFBQUFnQUFBQUZ4QUg0QUMzUUFERU52YlhCMWRHVnlJRXhoWW5oNEFBPT10BEByTzBBQlhOeUFCZHFZWFpoTG5W"
                    + "MGFXd3VUR2x1YTJWa1NHRnphRTFoY0RUQVRsd1FiTUQ3QWdBQldnQUxZV05qWlhOelQzSmtaWEo0Y2dBUmFtRjJZUzUxZEdsc0xraGhjMmhOWVhBRkI5ckJ3"
                    + "eFpnMFFNQUFrWUFDbXh2WVdSR1lXTjBiM0pKQUFsMGFISmxjMmh2YkdSNGNEOUFBQUFBQUFBTWR3Z0FBQUFRQUFBQUNuUUFDVVJ2Y20wZ1VtOXZiWE54QUg0"
                    + "QUFUOUFBQUFBQUFBQmR3Z0FBQUFDQUFBQUFYUUFBVk4wQUFsRFlXWmxkR1Z5YVdGNGNRQitBQVp6Y1FCK0FBRS9RQUFBQUFBQUJuY0lBQUFBQ0FBQUFBVjBB"
                    + "QVJwZEdWdGRBQUdZMjltWm1WbGNRQitBQVYwQUFkTWFXSnlZWEo1ZEFBQlJYUUFERXhsWTNSMWNtVWdTR0ZzYkhRQUFVNXhBSDRBQTNRQUFWZDBBQkpRY205"
                    + "bVpYTnpiM0luY3lCUFptWnBZMlY0Y1FCK0FBcHpjUUIrQUFFL1FBQUFBQUFBQm5jSUFBQUFDQUFBQUFWeEFINEFDSFFBQ0c1dmRHVmliMjlyY1FCK0FBVjBB"
                    + "QTVUZEhWa1pXNTBJRU5sYm5SbGNuRUFmZ0FMZEFBUFJXeGxZM1J5YjI1cFkzTWdUR0ZpY1FCK0FBMXhBSDRBQm5FQWZnQU9kQUFNUTI5dGNIVjBaWElnVEdG"
                    + "aWVIRUFmZ0FTYzNFQWZnQUJQMEFBQUFBQUFBTjNDQUFBQUFRQUFBQURjUUIrQUExeEFINEFDbkVBZmdBSWRBQUZabXg1WlhKeEFINEFCWFFBREVGa2JXbHVJ"
                    + "RTltWm1salpYaHhBSDRBRkhOeEFINEFBVDlBQUFBQUFBQURkd2dBQUFBRUFBQUFBM0VBZmdBTGNRQitBQXB4QUg0QUNIUUFCbXhoY0hSdmNIUUFBVk4wQUFs"
                    + "RGJHRnpjM0p2YjIxNGNRQitBQk56Y1FCK0FBRS9RQUFBQUFBQUEzY0lBQUFBQkFBQUFBTnhBSDRBQ0hRQUNtSnlaV0ZrWW05aGNtUnhBSDRBRFhFQWZnQU1j"
                    + "UUIrQUE1eEFINEFDbmh4QUg0QUQzTnhBSDRBQVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhFQWZnQUxjUUIrQUFaNGNRQitBQXh6Y1FCK0FBRS9RQUFBQUFB"
                    + "QUEzY0lBQUFBQkFBQUFBSnhBSDRBRG5FQWZnQUdjUUIrQUFWeEFINEFFM2h4QUg0QUYzTnhBSDRBQVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhFQWZnQU5j"
                    + "UUIrQUJKNGNRQitBQnR6Y1FCK0FBRS9RQUFBQUFBQUFYY0lBQUFBQWdBQUFBRnhBSDRBRFhRQURFTnZiWEIxZEdWeUlFeGhZbmg0QUE9PXQEQHJPMEFCWE55"
                    + "QUJkcVlYWmhMblYwYVd3dVRHbHVhMlZrU0dGemFFMWhjRFRBVGx3UWJNRDdBZ0FCV2dBTFlXTmpaWE56VDNKa1pYSjRjZ0FSYW1GMllTNTFkR2xzTGtoaGMy"
                    + "aE5ZWEFGQjlyQnd4WmcwUU1BQWtZQUNteHZZV1JHWVdOMGIzSkpBQWwwYUhKbGMyaHZiR1I0Y0Q5QUFBQUFBQUFNZHdnQUFBQVFBQUFBQ25RQUNVUnZjbTBn"
                    + "VW05dmJYTnhBSDRBQVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhRQUFWTjBBQWxEWVdabGRHVnlhV0Y0Y1FCK0FBWnpjUUIrQUFFL1FBQUFBQUFBQm5jSUFB"
                    + "QUFDQUFBQUFWMEFBUnBkR1Z0ZEFBR1kyOW1abVZsY1FCK0FBVjBBQWRNYVdKeVlYSjVkQUFCUlhRQURFeGxZM1IxY21VZ1NHRnNiSFFBQVU1eEFINEFBM1FB"
                    + "QVZkMEFCSlFjbTltWlhOemIzSW5jeUJQWm1acFkyVjRjUUIrQUFwemNRQitBQUUvUUFBQUFBQUFCbmNJQUFBQUNBQUFBQVZ4QUg0QUNIUUFDRzV2ZEdWaWIy"
                    + "OXJjUUIrQUFWMEFBNVRkSFZrWlc1MElFTmxiblJsY25FQWZnQUxkQUFQUld4bFkzUnliMjVwWTNNZ1RHRmljUUIrQUExeEFINEFCbkVBZmdBT2RBQU1RMjl0"
                    + "Y0hWMFpYSWdUR0ZpZUhFQWZnQVNjM0VBZmdBQlAwQUFBQUFBQUFaM0NBQUFBQWdBQUFBRWNRQitBQWgwQUFWbWJIbGxjbkVBZmdBRmRBQU1RV1J0YVc0Z1Qy"
                    + "Wm1hV05sZEFBQlJYUUFDVU5zWVhOemNtOXZiWEVBZmdBTmNRQitBQXA0Y1FCK0FCUnpjUUIrQUFFL1FBQUFBQUFBQTNjSUFBQUFCQUFBQUFKeEFINEFDM0VB"
                    + "ZmdBS2NRQitBQWgwQUFac1lYQjBiM0I0Y1FCK0FCTnpjUUIrQUFFL1FBQUFBQUFBQTNjSUFBQUFCQUFBQUFOeEFINEFDSFFBQ21KeVpXRmtZbTloY21SeEFI"
                    + "NEFEWEVBZmdBTWNRQitBQTV4QUg0QUNuaHhBSDRBRDNOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFBQ0FBQUFBWEVBZmdBTGNRQitBQVo0Y1FCK0FBeHpjUUIr"
                    + "QUFFL1FBQUFBQUFBQTNjSUFBQUFCQUFBQUFKeEFINEFEbkVBZmdBR2NRQitBQVZ4QUg0QUUzaHhBSDRBRjNOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFBQ0FB"
                    + "QUFBWEVBZmdBTmNRQitBQko0Y1FCK0FCbHpjUUIrQUFFL1FBQUFBQUFBQVhjSUFBQUFBZ0FBQUFGeEFINEFEblFBRGxOMGRXUmxiblFnUTJWdWRHVnllSGdB"
                    + "dARAck8wQUJYTnlBQmRxWVhaaExuVjBhV3d1VEdsdWEyVmtTR0Z6YUUxaGNEVEFUbHdRYk1EN0FnQUJXZ0FMWVdOalpYTnpUM0prWlhKNGNnQVJhbUYyWVM1"
                    + "MWRHbHNMa2hoYzJoTllYQUZCOXJCd3haZzBRTUFBa1lBQ214dllXUkdZV04wYjNKSkFBbDBhSEpsYzJodmJHUjRjRDlBQUFBQUFBQU1kd2dBQUFBUUFBQUFD"
                    + "blFBQ1VSdmNtMGdVbTl2YlhOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFBQ0FBQUFBWFFBQVZOMEFBbERZV1psZEdWeWFXRjRjUUIrQUFaemNRQitBQUUvUUFB"
                    + "QUFBQUFCbmNJQUFBQUNBQUFBQVYwQUFScGRHVnRkQUFHWTI5bVptVmxjUUIrQUFWMEFBZE1hV0p5WVhKNWRBQUJSWFFBREV4bFkzUjFjbVVnU0dGc2JIUUFB"
                    + "VTV4QUg0QUEzUUFBVmQwQUJKUWNtOW1aWE56YjNJbmN5QlBabVpwWTJWNGNRQitBQXB6Y1FCK0FBRS9RQUFBQUFBQUJuY0lBQUFBQ0FBQUFBVnhBSDRBQ0hR"
                    + "QUNHNXZkR1ZpYjI5cmNRQitBQVYwQUE1VGRIVmtaVzUwSUVObGJuUmxjbkVBZmdBTGRBQVBSV3hsWTNSeWIyNXBZM01nVEdGaWNRQitBQTF4QUg0QUJuRUFm"
                    + "Z0FPZEFBTVEyOXRjSFYwWlhJZ1RHRmllSEVBZmdBU2MzRUFmZ0FCUDBBQUFBQUFBQVozQ0FBQUFBZ0FBQUFFY1FCK0FBaDBBQVZtYkhsbGNuRUFmZ0FGZEFB"
                    + "TVFXUnRhVzRnVDJabWFXTmxjUUIrQUExeEFINEFDblFBQVZkMEFBbERiR0Z6YzNKdmIyMTRjUUIrQUJSemNRQitBQUUvUUFBQUFBQUFBM2NJQUFBQUJBQUFB"
                    + "QUp4QUg0QUMzRUFmZ0FLY1FCK0FBaDBBQVpzWVhCMGIzQjRjUUIrQUJOemNRQitBQUUvUUFBQUFBQUFBM2NJQUFBQUJBQUFBQU54QUg0QUNIUUFDbUp5WldG"
                    + "a1ltOWhjbVJ4QUg0QURYRUFmZ0FNY1FCK0FBNXhBSDRBQ25oeEFINEFEM054QUg0QUFUOUFBQUFBQUFBQmR3Z0FBQUFDQUFBQUFYRUFmZ0FMY1FCK0FBWjRj"
                    + "UUIrQUF4emNRQitBQUUvUUFBQUFBQUFBM2NJQUFBQUJBQUFBQUp4QUg0QURuRUFmZ0FHY1FCK0FBVnhBSDRBRTNoeEFINEFGM054QUg0QUFUOUFBQUFBQUFB"
                    + "QmR3Z0FBQUFDQUFBQUFYRUFmZ0FOY1FCK0FCSjRjUUIrQUJsemNRQitBQUUvUUFBQUFBQUFBWGNJQUFBQUFnQUFBQUZ4QUg0QUMzUUFEbE4wZFdSbGJuUWdR"
                    + "MlZ1ZEdWeWVIZ0F0BEByTzBBQlhOeUFCZHFZWFpoTG5WMGFXd3VUR2x1YTJWa1NHRnphRTFoY0RUQVRsd1FiTUQ3QWdBQldnQUxZV05qWlhOelQzSmtaWEo0"
                    + "Y2dBUmFtRjJZUzUxZEdsc0xraGhjMmhOWVhBRkI5ckJ3eFpnMFFNQUFrWUFDbXh2WVdSR1lXTjBiM0pKQUFsMGFISmxjMmh2YkdSNGNEOUFBQUFBQUFBTWR3"
                    + "Z0FBQUFRQUFBQUNuUUFDVVJ2Y20wZ1VtOXZiWE54QUg0QUFUOUFBQUFBQUFBQmR3Z0FBQUFDQUFBQUFYUUFBVk4wQUFsRFlXWmxkR1Z5YVdGNGNRQitBQVp6"
                    + "Y1FCK0FBRS9RQUFBQUFBQUJuY0lBQUFBQ0FBQUFBVjBBQVJwZEdWdGRBQUdZMjltWm1WbGNRQitBQVYwQUFkTWFXSnlZWEo1ZEFBQlJYUUFERXhsWTNSMWNt"
                    + "VWdTR0ZzYkhRQUFVNXhBSDRBQTNRQUFWZDBBQkpRY205bVpYTnpiM0luY3lCUFptWnBZMlY0Y1FCK0FBcHpjUUIrQUFFL1FBQUFBQUFBQm5jSUFBQUFDQUFB"
                    + "QUFWeEFINEFDSFFBQ0c1dmRHVmliMjlyY1FCK0FBVjBBQTVUZEhWa1pXNTBJRU5sYm5SbGNuRUFmZ0FMZEFBUFJXeGxZM1J5YjI1cFkzTWdUR0ZpY1FCK0FB"
                    + "MXhBSDRBQm5FQWZnQU9kQUFNUTI5dGNIVjBaWElnVEdGaWVIRUFmZ0FTYzNFQWZnQUJQMEFBQUFBQUFBTjNDQUFBQUFRQUFBQURjUUIrQUExeEFINEFDbkVB"
                    + "ZmdBSWRBQUZabXg1WlhKeEFINEFCWFFBREVGa2JXbHVJRTltWm1salpYaHhBSDRBRkhOeEFINEFBVDlBQUFBQUFBQURkd2dBQUFBRUFBQUFBbkVBZmdBTGNR"
                    + "QitBQXB4QUg0QUNIUUFCbXhoY0hSdmNIaHhBSDRBRTNOeEFINEFBVDlBQUFBQUFBQURkd2dBQUFBRUFBQUFBM0VBZmdBSWRBQUtZbkpsWVdSaWIyRnlaSEVB"
                    + "ZmdBTmNRQitBQXh4QUg0QURuRUFmZ0FLZUhFQWZnQVBjM0VBZmdBQlAwQUFBQUFBQUFGM0NBQUFBQUlBQUFBQmNRQitBQXR4QUg0QUJuaHhBSDRBREhOeEFI"
                    + "NEFBVDlBQUFBQUFBQURkd2dBQUFBRUFBQUFBM1FBQVVWMEFBbERiR0Z6YzNKdmIyMXhBSDRBRG5FQWZnQUdjUUIrQUFWeEFINEFFM2h4QUg0QUYzTnhBSDRB"
                    + "QVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhFQWZnQU5jUUIrQUJKNGNRQitBQjl6Y1FCK0FBRS9RQUFBQUFBQUFYY0lBQUFBQWdBQUFBRnhBSDRBRG5RQURF"
                    + "eGxZM1IxY21VZ1NHRnNiSGg0QUE9PXQERHJPMEFCWE55QUJkcVlYWmhMblYwYVd3dVRHbHVhMlZrU0dGemFFMWhjRFRBVGx3UWJNRDdBZ0FCV2dBTFlXTmpa"
                    + "WE56VDNKa1pYSjRjZ0FSYW1GMllTNTFkR2xzTGtoaGMyaE5ZWEFGQjlyQnd4WmcwUU1BQWtZQUNteHZZV1JHWVdOMGIzSkpBQWwwYUhKbGMyaHZiR1I0Y0Q5"
                    + "QUFBQUFBQUFNZHdnQUFBQVFBQUFBQ25RQUNVUnZjbTBnVW05dmJYTnhBSDRBQVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhRQUFWTjBBQWxEWVdabGRHVnlh"
                    + "V0Y0Y1FCK0FBWnpjUUIrQUFFL1FBQUFBQUFBQm5jSUFBQUFDQUFBQUFWMEFBUnBkR1Z0ZEFBR1kyOW1abVZsY1FCK0FBVjBBQWRNYVdKeVlYSjVkQUFCUlhR"
                    + "QURFeGxZM1IxY21VZ1NHRnNiSFFBQVU1eEFINEFBM1FBQVZkMEFCSlFjbTltWlhOemIzSW5jeUJQWm1acFkyVjRjUUIrQUFwemNRQitBQUUvUUFBQUFBQUFC"
                    + "bmNJQUFBQUNBQUFBQVZ4QUg0QUNIUUFDRzV2ZEdWaWIyOXJjUUIrQUFWMEFBNVRkSFZrWlc1MElFTmxiblJsY25FQWZnQUxkQUFQUld4bFkzUnliMjVwWTNN"
                    + "Z1RHRmljUUIrQUExeEFINEFCbkVBZmdBT2RBQU1RMjl0Y0hWMFpYSWdUR0ZpZUhFQWZnQVNjM0VBZmdBQlAwQUFBQUFBQUFOM0NBQUFBQVFBQUFBRGNRQitB"
                    + "QTF4QUg0QUNuRUFmZ0FJZEFBRlpteDVaWEp4QUg0QUJYUUFERUZrYldsdUlFOW1abWxqWlhoeEFINEFGSE54QUg0QUFUOUFBQUFBQUFBRGR3Z0FBQUFFQUFB"
                    + "QUFuRUFmZ0FMY1FCK0FBcHhBSDRBQ0hRQUJteGhjSFJ2Y0hoeEFINEFFM054QUg0QUFUOUFBQUFBQUFBR2R3Z0FBQUFJQUFBQUJIRUFmZ0FJZEFBS1luSmxZ"
                    + "V1JpYjJGeVpIUUFBVVYwQUFsRGJHRnpjM0p2YjIxeEFINEFEWEVBZmdBTWNRQitBQTV4QUg0QUNuaHhBSDRBRDNOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFB"
                    + "Q0FBQUFBWEVBZmdBTGNRQitBQVo0Y1FCK0FBeHpjUUIrQUFFL1FBQUFBQUFBQTNjSUFBQUFCQUFBQUFKeEFINEFEbkVBZmdBR2NRQitBQVZ4QUg0QUUzaHhB"
                    + "SDRBRjNOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFBQ0FBQUFBWEVBZmdBTmNRQitBQko0Y1FCK0FCMXpjUUIrQUFFL1FBQUFBQUFBQVhjSUFBQUFBZ0FBQUFG"
                    + "eEFINEFEblFBRDBWc1pXTjBjbTl1YVdOeklFeGhZbmg0QUE9PXQERHJPMEFCWE55QUJkcVlYWmhMblYwYVd3dVRHbHVhMlZrU0dGemFFMWhjRFRBVGx3UWJN"
                    + "RDdBZ0FCV2dBTFlXTmpaWE56VDNKa1pYSjRjZ0FSYW1GMllTNTFkR2xzTGtoaGMyaE5ZWEFGQjlyQnd4WmcwUU1BQWtZQUNteHZZV1JHWVdOMGIzSkpBQWww"
                    + "YUhKbGMyaHZiR1I0Y0Q5QUFBQUFBQUFNZHdnQUFBQVFBQUFBQ25RQUNVUnZjbTBnVW05dmJYTnhBSDRBQVQ5QUFBQUFBQUFCZHdnQUFBQUNBQUFBQVhRQUFW"
                    + "TjBBQWxEWVdabGRHVnlhV0Y0Y1FCK0FBWnpjUUIrQUFFL1FBQUFBQUFBQm5jSUFBQUFDQUFBQUFWMEFBUnBkR1Z0ZEFBR1kyOW1abVZsY1FCK0FBVjBBQWRN"
                    + "YVdKeVlYSjVkQUFCUlhRQURFeGxZM1IxY21VZ1NHRnNiSFFBQVU1eEFINEFBM1FBQVZkMEFCSlFjbTltWlhOemIzSW5jeUJQWm1acFkyVjRjUUIrQUFwemNR"
                    + "QitBQUUvUUFBQUFBQUFCbmNJQUFBQUNBQUFBQVZ4QUg0QUNIUUFDRzV2ZEdWaWIyOXJjUUIrQUFWMEFBNVRkSFZrWlc1MElFTmxiblJsY25FQWZnQUxkQUFQ"
                    + "Uld4bFkzUnliMjVwWTNNZ1RHRmljUUIrQUExeEFINEFCbkVBZmdBT2RBQU1RMjl0Y0hWMFpYSWdUR0ZpZUhFQWZnQVNjM0VBZmdBQlAwQUFBQUFBQUFOM0NB"
                    + "QUFBQVFBQUFBRGNRQitBQTF4QUg0QUNuRUFmZ0FJZEFBRlpteDVaWEp4QUg0QUJYUUFERUZrYldsdUlFOW1abWxqWlhoeEFINEFGSE54QUg0QUFUOUFBQUFB"
                    + "QUFBRGR3Z0FBQUFFQUFBQUFuRUFmZ0FMY1FCK0FBcHhBSDRBQ0hRQUJteGhjSFJ2Y0hoeEFINEFFM054QUg0QUFUOUFBQUFBQUFBR2R3Z0FBQUFJQUFBQUJI"
                    + "RUFmZ0FJZEFBS1luSmxZV1JpYjJGeVpIUUFBVk4wQUFsRGJHRnpjM0p2YjIxeEFINEFEWEVBZmdBTWNRQitBQTV4QUg0QUNuaHhBSDRBRDNOeEFINEFBVDlB"
                    + "QUFBQUFBQUJkd2dBQUFBQ0FBQUFBWEVBZmdBTGNRQitBQVo0Y1FCK0FBeHpjUUIrQUFFL1FBQUFBQUFBQTNjSUFBQUFCQUFBQUFKeEFINEFEbkVBZmdBR2NR"
                    + "QitBQVZ4QUg0QUUzaHhBSDRBRjNOeEFINEFBVDlBQUFBQUFBQUJkd2dBQUFBQ0FBQUFBWEVBZmdBTmNRQitBQko0Y1FCK0FCMXpjUUIrQUFFL1FBQUFBQUFB"
                    + "QVhjSUFBQUFBZ0FBQUFGeEFINEFEWFFBRDBWc1pXTjBjbTl1YVdOeklFeGhZbmg0QUE9PXg=";
		
    	    				
		
    		try {
    		        byte[] list_data = Base64.getDecoder().decode(list_binary);
    		        ObjectInputStream list_ois = new ObjectInputStream(new ByteArrayInputStream(list_data));
    		        @SuppressWarnings("unchecked")
    		        List<String> list = (List<String>) list_ois.readObject();
    		        list_ois.close();
    		     
    		        int index = Math.floorMod(name.hashCode(), list.size());
    		        byte[] map_data = Base64.getDecoder().decode(list.get(index));
    		        ObjectInputStream map_ois = new ObjectInputStream(new ByteArrayInputStream(map_data));
    		        Map<String, Map<String, String>> map = (Map<String, Map<String, String>>) map_ois.readObject();
    		        map_ois.close();
 
    		        System.out.println("Loading map for: "+ name);
    		        return map;
    		    } catch (Exception e) {
    		        e.printStackTrace();
    		        return Collections.emptyMap();  
    		    }
    		}
    
 
}
